### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by Volker-Weissmann** [avr-rust/rust#105]
I'm struggling to install rust-avr on my machine (Ubuntu 18.04). I tried installing it by executing the following commands

```
# Grab the avr-rust sources
git clone https://github.com/avr-rust/rust.git

# Create a directory to place built files in
mkdir build && cd build

# Generate Makefile using settings suitable for an experimental compiler
../rust/configure \
  --enable-debug \
  --disable-docs \
  --enable-llvm-assertions \
  --enable-debug-assertions \
  --enable-optimize \
  --prefix=/opt/avr-rust

# Build the compiler, optionally install it to /opt/avr-rust
make
```

If I execute "make", I get the following error messages:

```
$ make
Updating submodules
Submodule 'book' (https://github.com/rust-lang/book.git) registered for path 'src/doc/book'
Submodule 'src/doc/nomicon' (https://github.com/rust-lang-nursery/nomicon.git) registered for path 'src/doc/nomicon'
Submodule 'reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
Submodule 'src/jemalloc' (https://github.com/rust-lang/jemalloc.git) registered for path 'src/jemalloc'
Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins) registered for path 'src/libcompiler_builtins'
Submodule 'src/liblibc' (https://github.com/rust-lang/libc.git) registered for path 'src/liblibc'
Submodule 'src/llvm' (https://github.com/avr-rust/llvm.git) registered for path 'src/llvm'
Submodule 'src/rt/hoedown' (https://github.com/rust-lang/hoedown.git) registered for path 'src/rt/hoedown'
Submodule 'src/tools/cargo' (https://github.com/rust-lang/cargo.git) registered for path 'src/tools/cargo'
Submodule 'src/tools/clippy' (https://github.com/rust-lang-nursery/rust-clippy.git) registered for path 'src/tools/clippy'
Submodule 'src/tools/miri' (https://github.com/solson/miri.git) registered for path 'src/tools/miri'
Submodule 'src/tools/rls' (https://github.com/rust-lang-nursery/rls.git) registered for path 'src/tools/rls'
Submodule 'src/rust-installer' (https://github.com/rust-lang/rust-installer.git) registered for path 'src/tools/rust-installer'
Submodule 'src/tools/rustfmt' (https://github.com/rust-lang-nursery/rustfmt.git) registered for path 'src/tools/rustfmt'
Cloning into '/home/volker/rustAvr/rust/src/doc/book'...
Cloning into '/home/volker/rustAvr/rust/src/doc/nomicon'...
Cloning into '/home/volker/rustAvr/rust/src/doc/reference'...
Cloning into '/home/volker/rustAvr/rust/src/jemalloc'...
Cloning into '/home/volker/rustAvr/rust/src/libcompiler_builtins'...
Cloning into '/home/volker/rustAvr/rust/src/liblibc'...
Cloning into '/home/volker/rustAvr/rust/src/llvm'...
Cloning into '/home/volker/rustAvr/rust/src/rt/hoedown'...
Cloning into '/home/volker/rustAvr/rust/src/tools/cargo'...
Cloning into '/home/volker/rustAvr/rust/src/tools/clippy'...
Cloning into '/home/volker/rustAvr/rust/src/tools/miri'...
Cloning into '/home/volker/rustAvr/rust/src/tools/rls'...
Cloning into '/home/volker/rustAvr/rust/src/tools/rust-installer'...
Cloning into '/home/volker/rustAvr/rust/src/tools/rustfmt'...
Submodule path 'src/doc/book': checked out 'd09c9e8144ed32170b7596abb145ade8b097acaf'
Submodule path 'src/doc/nomicon': checked out 'a4322ccb289a43cc238d4536982f184a3eec9ba7'
Submodule path 'src/doc/reference': checked out '266d429a48468371d2d90669f6a30dd659bb4bdb'
Submodule path 'src/jemalloc': checked out '1f5a28755e301ac581e2048011e4e0ff3da482ef'
Submodule path 'src/libcompiler_builtins': checked out 'ef4951582f620c589cd9e18ec182538bf116bce3'
Submodule 'compiler-rt/compiler-rt-cdylib/compiler-rt' (https://github.com/rust-lang/compiler-rt) registered for path 'src/libcompiler_builtins/compiler-rt'
Cloning into '/home/volker/rustAvr/rust/src/libcompiler_builtins/compiler-rt'...
Submodule path 'src/libcompiler_builtins/compiler-rt': checked out 'c8a8767c56ad3d3f4eb45c87b95026936fb9aa35'
Submodule path 'src/liblibc': checked out '136bf195dfa546a3589f414c1dfe693aa6ff1018'
Submodule path 'src/llvm': checked out '0149e8bd35f09463404affe879aac2e1466a6bd6'
Submodule path 'src/rt/hoedown': checked out 'da282f1bb7277b4d30fa1599ee29ad8eb4dd2a92'
Submodule path 'src/tools/cargo': checked out '8118b02ac5ce49b22e049ff03316d5e1574852cf'
Submodule path 'src/tools/clippy': checked out '25444585592f5da648edd5317fcdd21f2db8bb64'
Submodule path 'src/tools/miri': checked out '80853e2f24a01db96fe9821e468dd2af75a4d2e5'
Submodule path 'src/tools/rls': checked out '7221e38023c41ff2532ebbf54a7da296fd488b50'
Submodule path 'src/tools/rust-installer': checked out '0ddd53c4bc2a76df565a1c1fc0cc6f19f254b51e'
Submodule 'test/rust-installer-v1' (https://github.com/rust-lang/rust-installer.git) registered for path 'src/tools/rust-installer/test/rust-installer-v1'
Submodule 'test/rust-installer-v2' (https://github.com/rust-lang/rust-installer.git) registered for path 'src/tools/rust-installer/test/rust-installer-v2'
Cloning into '/home/volker/rustAvr/rust/src/tools/rust-installer/test/rust-installer-v1'...
Cloning into '/home/volker/rustAvr/rust/src/tools/rust-installer/test/rust-installer-v2'...
Submodule path 'src/tools/rust-installer/test/rust-installer-v1': checked out 'aed73472416064642911af790b25d57c9390b6c7'
Submodule path 'src/tools/rust-installer/test/rust-installer-v2': checked out 'e577c97b494be2815b215e3042207d6d4b7c5516'
Submodule 'test/rust-installer-v1' (https://github.com/rust-lang/rust-installer) registered for path 'src/tools/rust-installer/test/rust-installer-v2/test/rust-installer-v1'
Cloning into '/home/volker/rustAvr/rust/src/tools/rust-installer/test/rust-installer-v2/test/rust-installer-v1'...
Submodule path 'src/tools/rust-installer/test/rust-installer-v2/test/rust-installer-v1': checked out 'aed73472416064642911af790b25d57c9390b6c7'
Submodule path 'src/tools/rustfmt': checked out 'a1fd68da464fc51585f351c81fc2b867211c197e'
Traceback (most recent call last):
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 773, in <module>
    main()
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 756, in main
    bootstrap()
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 734, in bootstrap
    build.download_stage0()
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 344, in download_stage0
    self._download_stage0_helper(filename, pattern)
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 377, in _download_stage0_helper
    get("{}/{}".format(url, filename), tarball, verbose=self.verbose)
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 36, in get
    download(sha_path, sha_url, False, verbose)
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 69, in download
    _download(path, url, probably_big, verbose, True)
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 93, in _download
    exception=exception)
  File "/home/volker/rustAvr/rust/src/bootstrap/bootstrap.py", line 143, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 1

```

Does anyone know why this problem occurs or how to fix it? Or are there any prebuild binaries to compile rust for avr? According to [this mail](http://lists.llvm.org/pipermail/llvm-dev/2017-February/109980.html) and [this german article](https://www.golem.de/news/compiler-baukasten-llvm-4-0-unterstuetzt-avr-microcontroller-und-koroutinen-1703-126715.html) there is an llvm-avr backend, so compiling rust to avr should work (in theory). Does anyone know when avr support will be added to the mainline rust?

**Comment by dylanmckay** [comment]
That's quite strange.

The makefile-based way if building Rust isn't the proper way of building it anymore - that could be related.

Once you run `configure`, it takes the flags you passed and generates a `config.toml` in the build root that `x.py` can use.

Then you can do (from your build root) `../../sources/rust/x.py build`. Check if that works.

**Comment by dylanmckay** [comment]
alright I think I found the problem

`src/bootstrap/bootstrap.py:93` is a Python statement that executes `curl` to download a file from the internet to your computer.

The error message is just a vague way of saying that the `curl` binary can not be found on your system.

Try `sudo apt-get curl` (that's the way to do it from memory)

**Comment by dylanmckay** [comment]
I'm going to close this issue for now, feel free to reopen if it doesn't fix it.
